import type { Metadata } from "next";
import "./globals.css";
import { ApolloWrapper } from "@/apollo/apollo-wrapper";
import { Providers } from "./providers";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";

export const metadata: Metadata = {
  title: "Rick & Morty API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-background text-foreground antialiased flex flex-col">
        <ApolloWrapper>
          <Providers>
            <Header />
            <main className="flex-1 mx-auto py-4 ">
              {children}
            </main>
            <Footer />
          </Providers>
        </ApolloWrapper>
      </body>
    </html>
  );
}
